name: AzoxMenu
version: '${project.version}'
main: net.azox.menu.AzoxMenu
api-version: '1.21'
author: ximotu
description: A scoreboard sidebar plugin with player stats, news, and music.

permissions:
  azox.admin:
    description: Allows reloading the plugin configuration.
    default: op
  azox.news:
    description: Allows managing news broadcasts.
    default: op
  azox.menu:
    description: Allows controlling music playback.
    default: true
